# Generated by Django 2.2.12 on 2022-06-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20220605_0810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
