# Generated by Django 2.2.12 on 2022-04-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='static/auctions')),
                ('maker', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('category', models.CharField(choices=[('FS', 'Fashion'), ('HM', 'Home and Living'), ('EL', 'Electronics'), ('TH', 'Toys and Hobbies'), ('Al', 'Arts and Literature'), ('MS', 'Music and Sports'), ('OT', 'Other Categories')], max_length=2)),
            ],
        ),
    ]
