# Generated by Django 2.2.12 on 2022-04-21 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220420_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lsiting', to='auctions.Listing'),
        ),
    ]
