# Generated by Django 2.2.12 on 2022-04-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20220424_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Home and Living', 'Home and Living'), ('Electronics and Vehicles', 'Electronics and Vehicles'), ('Toys and Hobbies', 'Toys and Hobbies'), ('Arts and Literature', 'Arts and Literature'), ('Music and Sports', 'Music and Sports'), ('Other Categories', 'Other Categories')], max_length=2),
        ),
    ]
